In [1]:
#(1) 로지스틱 회귀 분석을 이용한 유방암 진단 프로젝트

# 1)데이터 수집
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer

b_cancer = load_breast_cancer()
b_cancer

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [2]:
# 2)데이터 수집 및 탐색
print(b_cancer.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [3]:
b_cancer_df = pd.DataFrame(b_cancer.data,columns=b_cancer.feature_names)
b_cancer_df['diagnosis'] = b_cancer.target
b_cancer_df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  diagnosis  
0          0.4601                  0.11890          0  
1          0.2750                  0.08902          0  
2          0.3613                  0.08758          0  
3          0.6638                  0.17300          0  
4          0.2364                  0.07678          0  

[5 rows x 31 columns]

In [4]:
print('유방안 진단 데이터셋 크기 : ',b_cancer_df.shape)

유방안 진단 데이터셋 크기 :  (569, 31)


In [5]:
b_cancer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
b_cancer_scaled = scaler.fit_transform(b_cancer.data)

In [7]:
print(b_cancer_scaled[0])

[ 1.09706398 -2.07333501  1.26993369  0.9843749   1.56846633  3.28351467
  2.65287398  2.53247522  2.21751501  2.25574689  2.48973393 -0.56526506
  2.83303087  2.48757756 -0.21400165  1.31686157  0.72402616  0.66081994
  1.14875667  0.90708308  1.88668963 -1.35929347  2.30360062  2.00123749
  1.30768627  2.61666502  2.10952635  2.29607613  2.75062224  1.93701461]


In [8]:
# 3) 분석 모델 구축 : 로지스틱 회귀를 이용한 이진 분류 모델
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [9]:
# X,Y 설정하기
Y = b_cancer_df['diagnosis']
X = b_cancer_scaled

In [10]:
#훈련용 데이터와 평가용 데이터로 분할 7:3
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=0)
X_train

array([[-0.74902829, -1.09363975, -0.74055999, ..., -0.61357437,
         0.06510643,  0.43524596],
       [-1.03304249, -0.15815877, -1.03424611, ..., -0.75107054,
        -1.11263786, -0.30621768],
       [-0.5331775 , -0.31407227, -0.56426593, ..., -0.49480691,
         0.34336469, -0.14551181],
       ...,
       [-1.33239345, -0.22564372, -1.32422512, ..., -0.97581512,
        -0.72275273, -0.14329518],
       [-1.25173342, -0.24891439, -1.28674204, ..., -1.74506282,
        -1.60444316, -1.01720262],
       [-0.74334801,  1.07984094, -0.71872918, ..., -0.27523937,
        -1.2760337 ,  0.1869831 ]])

In [11]:
# 로지스틱 회귀 분석 : (1)모델 생성
lr_b_cancer = LogisticRegression()

In [12]:
# 로지스틱 회귀 분석 : (2)모델 훈련
lr_b_cancer.fit(X_train,Y_train)

LogisticRegression()

In [13]:
# 로지스틱 회귀 분석 : (3)평가 데이터에 대한 예측수행 -> 예측 결과 Y_predict 구하기
Y_predict = lr_b_cancer.predict(X_test)
Y_predict

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1])

In [14]:
# (4) 결과 분석
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import precision_score,recall_score,f1_score,roc_auc_score

In [15]:
# 오차행렬
confusion_matrix(Y_test,Y_predict)

array([[ 60,   3],
       [  1, 107]], dtype=int64)

In [16]:
accuracy_score = accuracy_score(Y_test,Y_predict)
precision = precision_score(Y_test,Y_predict)
recall  =recall_score(Y_test,Y_predict)
f1 = f1_score(Y_test,Y_predict)
roc_auc = roc_auc_score(Y_test,Y_predict)

In [18]:
print('정확도:{0:.3f},정밀도:{1:.3f},재현율:{2:.3f},F1:{3:.3f}'.format(accuracy_score,precision,recall,f1))

정확도:0.977,정밀도:0.973,재현율:0.991,F1:0.982


In [19]:
print('ROC_AUC:{0:.3f}'.format(roc_auc))

ROC_AUC:0.972


In [ ]:
# 정확도 (예측결과와 실제값이 동일한 건수/전체 데이터 수
#       => TP+TN/TP+FP+FN+TN)
# 정밀도 예측이 Positive(TP,FP)인 것 중에서 참(TP)인 비율
# ==> TP/(TP+FP)

# 재현율 실제값이 Positive(TP,FP)인 것 중에서 참(TP)인 비율
# ==> TP/ (TP+FN)

#F1 스코어 정밀도와 재현율 결합
# ===> 2 * (정밀도*재현율)/(정밀도+재현율)

#ROC 기반 AUC 스코어 : 오차행렬의 FPR(FP rate)이 변할 때 TPR(TP rate)이 어떻게 변하는지
#FPR(FP rate) : 실제 Negative인 데이터를 Positive로 예측한 비율
#TPR : 실제  Positive인 데이터를 참(true)으로 예측한 비율(재현율)