In [ ]:
# ML 알고리즘에 데이터 입력 
#결측갑(Null,NaN) 허용 안함 ==> 다른 값으로 변환
#문자열 값 입력값으로 허용 안함 ==> 인코딩해서 숫자형으로 변환

In [4]:
#1. 데이터 인코딩
# (1) 레이블 인코딩(Label Encoder) ==> 카테고리 피처를 코드형 숫자로 변환
# LabelEncoder 
from sklearn.preprocessing import LabelEncoder
 
items = [ 'TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변화값 : ',labels)

인코딩 변화값 :  [0 1 4 5 3 3 2 2]


In [5]:
#classes_ : 변환 된 인코딩 값에 대한 원본 값을 가지고 있음
print('인코딩 클래스 : ',encoder.classes_)

인코딩 클래스 :  ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [7]:
# (2)원-핫 인코딩(One-Hot Encoding)
# OneHotEncoder 변환하기 전에 모든 문자열 값이 숫자형으로 변환이 되어 있어야 함
import numpy as np
items = [ 'TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()
encoder.fit(items)
lables = encoder.transform(items)
labels = labels.reshape(-1,1)
lables

array([0, 1, 4, 5, 3, 3, 2, 2])

In [10]:
#원-핫 인코딩 적용
from sklearn.preprocessing import OneHotEncoder

oh_encoder = OneHotEncoder(categories='auto')
oh_encoder.fit(labels)
oh_labels=oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print(oh_labels.shape)


원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)


In [12]:
import pandas as pd
df =pd.DataFrame({'items' : [ 'TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
df

items
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [13]:
#get_dummies() : 판다스에서 이용할 수 있는 원핫 인코딩 API
#사이킷런의 OneHotEncoder와는 달리 문자열 카테고리 값을 숫자형으로 변환할 필요 없이 바로 변환됨


In [14]:
#2. 피처 스케일링과 정규화
#피터 스케일링(Feature Scaling): 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업(표준화,정규화 등)
#ㄷ정규화 : 모든 값이 0~1
#표준화(Standardization):데이터 피처의 각각의 평균이 0이고 분산이 1인 가우시안 정규분포를 가진 값으로 변환 평균을 빼고 분산으로 나눈 값
#(1) StandardScaler : 표준화를 쉽게 지원하기 위한 클래스로 개별 피처를 평균이 0, 분산이 1인 값으로 변환

In [16]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data,columns=iris.feature_names)
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [17]:
print('feature들의 평균 값 :')
print(iris_df.mean())

feature들의 평균 값 :
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64


In [18]:
print('\nfeature들의 분산 값 :')
print(iris_df.var())


feature들의 분산 값 :
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [20]:
# StandardScaler를 이용하여 표준화
from sklearn.preprocessing import StandardScaler
#StandardScaler 객체 생성
scaler = StandardScaler()
#StandardScaler로 데이터 세트변환, fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

#데이터 프레임으로 변환
iris_df_scaled = pd.DataFrame(data = iris_scaled,columns=iris.feature_names)
iris_df_scaled.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.900681          1.019004          -1.340227         -1.315444
1          -1.143017         -0.131979          -1.340227         -1.315444
2          -1.385353          0.328414          -1.397064         -1.315444
3          -1.506521          0.098217          -1.283389         -1.315444
4          -1.021849          1.249201          -1.340227         -1.315444

In [23]:
print('feature들의 평균 값 :')
print(iris_df_scaled.mean())

feature들의 평균 값 :
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64


In [24]:
print('\nfeature들의 분산 값 :')
print(iris_df_scaled.var())


feature들의 분산 값 :
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [28]:
# (2) MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

#MinMaxScaler 객체 생성
scaler = MinMaxScaler()
#fit(),transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

In [29]:
#Dataframe 으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled,columns=iris.feature_names)
iris_df_scaled.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.222222          0.625000           0.067797          0.041667
1           0.166667          0.416667           0.067797          0.041667
2           0.111111          0.500000           0.050847          0.041667
3           0.083333          0.458333           0.084746          0.041667
4           0.194444          0.666667           0.067797          0.041667

In [30]:
print('feature들의 최솟값 :')
print(iris_df_scaled.min())
print('\nfeature들의 최댓값 :')
print(iris_df_scaled.max())

feature들의 최솟값 :
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최댓값 :
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
